name: Build and Deploy containers

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
      - main

jobs:
  deploy-test-containers:
    runs-on: ubuntu-latest
    name: Build Smeagle Container
    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Build Base Smeagle Container
        run: |
            docker build -t ghcr.io/buildsi/smeagle .
            version=$(cat VERSION)
            printf "Found version ${version}"
            docker tag ghcr.io/buildsi/smeagle:latest ghcr.io/buildsi/smeagle:${version}
            docker images | grep smeagle

      - name: Build Smeagle Pytest
        run: |
            docker build -f docker/Dockerfile.pytest -t ghcr.io/buildsi/smeagle-pytest .
            version=$(cat VERSION)
            docker tag ghcr.io/buildsi/smeagle-pytest:latest ghcr.io/buildsi/smeagle-pytest:${version}
            docker images | grep smeagle

      - name: Login and Deploy Test Container
        if: (github.event_name != 'pull_request')
        run: |
            docker images
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            version=$(cat VERSION)
            docker push ghcr.io/buildsi/smeagle:latest
            docker push ghcr.io/buildsi/smeagle:${version}
            docker push ghcr.io/buildsi/smeagle-pytest:latest
            docker push ghcr.io/buildsi/smeagle-pytest:${version}
