name: Documentation

on:
  push:
    branches: [main]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    container: ghcr.io/autamus/dyninst:master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget g++ libssl-dev git libtbb-dev python3-dev build-essential \
              python3-jinja2 python3-pygments ghostscript doxygen python3-yaml python3-pip curl

          CMAKE=3.20.2
          curl -s -L https://github.com/Kitware/CMake/releases/download/v$CMAKE/cmake-$CMAKE-linux-x86_64.sh > cmake.sh && \
          sh cmake.sh --prefix=/usr/local --skip-license && \
          rm cmake.sh

          cd /tmp
          git clone https://github.com/cheshirekow/cmake_format
          cd cmake_format
          pip3 install .

      - name: Build
        run: |
            make docs
            touch ./build/doc/doxygen/html/.nojekyll
          
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/doxygen/html
