name: Documentation

on:
  push:
    branches: [main]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    container: ghcr.io/autamus/dyninst:master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget g++ libssl-dev git libtbb-dev python3-dev build-essential \
              python3-jinja2 python3-pygments ghostscript doxygen python3-yaml python3-pip

          cd /tmp
          wget https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2.tar.gz
          tar -xzvf cmake-3.20.2.tar.gz && \
          cd cmake-3.20.2/
          ./bootstrap
          make
          make install

          cd /tmp
          git clone https://github.com/cheshirekow/cmake_format
          cd cmake_format
          pip3 install .

      - name: Build
        run: |
            make docs
            touch ./build/doc/doxygen/html/.nojekyll
          
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/doxygen/html
