name: Style

on:
  push:
    branches:
      - main
  pull_request: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t smeagle .
      - name: Check format
        run: docker run -it --entrypoint make smeagle fmt
